SOURCE_MAKE=. ./.make/make.sh

provision:
	@${SOURCE_MAKE} && provision

b: build
build:
	@${SOURCE_MAKE} && build

d: deploy
deploy:
	@${SOURCE_MAKE} && deploy

i: info
info:
	@${SOURCE_MAKE} && info

s: gen
gen:
	@${SOURCE_MAKE} && gen

p: package
package:
	@${SOURCE_MAKE} && package

t: test
test:
	@${SOURCE_MAKE} && test