apiVersion: v1
kind: ServiceAccount
metadata:
  name: metamate
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: read-services
rules:
  - apiGroups: [""]
    resources: ["services",]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metamate-read-services
  namespace: default
subjects:
  - kind: ServiceAccount
    name: metamate
roleRef:
  kind: Role
  name: read-services
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metamate
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metamate
  template:
    metadata:
      labels:
        name: metamate
    spec:
      serviceAccountName: metamate
      containers:
        - name: metamate
          image: metamatex/metamate:latest
          command: ["./metamate"]
          args: ["serve"]
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /metamate.yaml
              subPath: metamate.yaml
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: metamate
spec:
  selector:
    name: metamate
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443