project_name: metactl
before:
  hooks:
    - go mod download
    - go generate ./...
    - go mod tidy
builds:
- main: ./cmd/metactl/main.go
  env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'