apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hackernews-svc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hackernews-svc
    spec:
      containers:
        - name: hackernews-svc
          image: metamatex/hackernews-svc:latest
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hackernews-svc
  annotations:
    metamate.io/v0.service.transport: httpjson
    metamate.io/v0.service.port: "80"
spec:
  selector:
    name: hackernews-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80