package fieldnames

const (
	Mode            = "mode"
	Auth            = "auth"
	ClientAccount   = "clientAccount"
	Select          = "select"
	Meta            = "meta"
	Input           = "input"
	Output          = "output"
	Service         = "service"
	SdkVersion      = "sdkVersion"
	Wraps           = "wraps"
	Services        = "services"
	Errors          = "errors"
	Message         = "message"
	Token           = "token"
	Password        = "password"
	Cache           = "cache"
	Pages           = "pages"
	Id              = "id"
	Value           = "value"
	Ids             = "ids"
	ServiceId       = "serviceId"
	Stage           = "stage"
	Method          = "method"
	Requester       = "requester"
	Data            = "data"
	Local           = "local"
	Hash            = "hash"
	Name            = "name"
	ServiceName     = "serviceName"
	AlternativeIds  = "alternativeIds"
	Kind            = "kind"
	Modifier        = "modifier"
	Endpoints       = "endpoints"
	Count           = "count"
	Collection      = "collection"
	Archive         = "archive"
	Permanent       = "permanent"
	Pagination      = "pagination"
	NotCount        = "notCount"
	NotPagination   = "notPagination"
	Relationships   = "relationships"
	Relation        = "relation"
	Relations       = "relations"
	Operation       = "operation"
	Me              = "me"
	CreatedAt       = "createdAt"
	UpdatedAt       = "updatedAt"
	All             = "all"
	Every           = "every"
	Some            = "some"
	None            = "none"
	Port            = "port"
	Transport       = "transport"
	Url             = "url"
	Host            = "host"
	Handle          = "handle"
	Whatevers       = "whatevers"
	BlueWhatevers   = "blueWhatevers"
	ClientRequest   = "clientRequest"
	ServiceRequest  = "serviceRequest"
	ServiceResponse = "serviceResponse"
	ClientResponse  = "clientResponse"
	Post            = "post"
	Get             = "get"
	Put             = "put"
	Delete          = "delete"
	IsVirtual       = "isVirtual"
)

const (
	CaseSensitive = "caseSensitive"
	Set           = "set"
	Search        = "search"
	NotSet        = "notSet"
	Is            = "is"
	Not           = "not"
	Contains      = "contains"
	Context       = "context"
	NotContains   = "notContains"
	StartsWith    = "startsWith"
	NotStartsWith = "notStartsWith"
	EndsWith      = "endsWith"
	NotEndsWith   = "notEndsWith"
	In            = "in"
	NotIn         = "notIn"
	And           = "and"
	Or            = "or"
	Lt            = "lt"
	Lte           = "lte"
	Gt            = "gt"
	Gte           = "gte"
)

const (
	Filter        = "filter"
	Sort          = "sort"
	ServiceFilter = "serviceFilter"
)

const (
	StringField  = "stringField"
	Int32Field   = "int32Field"
	Float64Field = "float64Field"
	BoolField    = "boolField"
	EnumField    = "enumField"
	UnionField   = "unionField"
	StringList   = "stringList"
	Int32List    = "int32List"
	Float64List  = "float64List"
	BoolList     = "boolList"
	EnumList     = "enumList"
)
