project_name: metamatemono
#before:
#  hooks:
#    - go mod download
builds:
- main: ./metactl/cmd/metactl/main.go
  binary: metactl
  id: metactl
  env:
  - CGO_ENABLED=0
- main: ./metamate/cmd/metamate/main.go
  binary: metamate
  id: metamate
  env:
    - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch