project_name: metamate
builds:
- main: ./metactl/cmd/metactl/main.go
  binary: metactl
  id: metactl
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  ignore:
  - goos: darwin
    goarch: 386
- main: ./metamate/cmd/metamate/main.go
  binary: metamate
  id: metamate
  env:
    - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
brews:
- name: metactl
  github:
    owner: metamatex
    name: homebrew-taps
  commit_author:
    name: ppwfx
    email: ph.woerdehoff@gmail.com
  homepage: "https://metamate.io"
  install: |
    bin.install "metactl"
dockers:
- image_templates:
  - 'metamatex/metamate:{{ .Tag }}'
  - 'metamatex/metamate:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
  - 'metamatex/metamate:latest'
  dockerfile: .make/Dockerfile
  binaries:
  - metamate
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--label=repository=http://github.com/metamatex/metamatemono"
  - "--label=homepage=http://metamate.io"