SOURCE_MAKE=. ./.make/make.sh
SHELL := /bin/bash

build:
	@${SOURCE_MAKE} && build

prepare:
	@${SOURCE_MAKE} && prepare

chore:
	@${SOURCE_MAKE} && chore

release:
	@${SOURCE_MAKE} && release

deploy:
	@${SOURCE_MAKE} && deploy

test:
	@${SOURCE_MAKE} && test