name: release-test
on: ["push"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "::add-path::$GITHUB_WORKSPACE/bin"
      - run: mkdir $GITHUB_WORKSPACE/bin
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl
      - run: mv kubectl $GITHUB_WORKSPACE/bin/kubectl
      - run: chmod +x $GITHUB_WORKSPACE/bin/kubectl
      - run: mkdir $HOME/.kube
      - run: echo "${{ secrets.METAMATE_ONE_KUBECONFIG }}" > $HOME/.kube/config
      - run: (cd metamate && make deploy)