name: test
on:
  push:
  pull_request:
jobs:
  testGeneric:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - run: (cd generic && make test)
  testMetaMate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - run: (cd metamate && make test)